# Generated by Django 2.2 on 2019-09-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_orderend_err_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderend',
            old_name='latitude',
            new_name='end_latitude',
        ),
        migrations.RenameField(
            model_name='orderend',
            old_name='longitude',
            new_name='end_longitude',
        ),
        migrations.RenameField(
            model_name='orderstart',
            old_name='latitude',
            new_name='start_latitude',
        ),
        migrations.RenameField(
            model_name='orderstart',
            old_name='longitude',
            new_name='start_longitude',
        ),
    ]
