# Generated by Django 2.2 on 2019-11-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20190923_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstart',
            name='invoice_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderstart',
            name='status',
            field=models.IntegerField(choices=[(0, 'No_Status'), (1, 'Normal'), (2, 'Start_Ng'), (3, 'End_Ng'), (4, 'StartEnd_Ng')], default=0),
        ),
    ]
