# Generated by Django 2.2 on 2019-11-08 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBatch',
            fields=[
                ('batch_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LowerPayment',
            fields=[
                ('serial_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('invoice_org', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('channel', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hash_value', models.BooleanField(default=False)),
                ('txid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('serial_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('goods_owner', models.CharField(max_length=100)),
                ('goods_name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('cube', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('task_state', models.BooleanField(default=True)),
                ('router', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hash_value', models.BooleanField(default=False)),
                ('txid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UpperPayment',
            fields=[
                ('serial_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('invoice_org', models.CharField(max_length=100)),
                ('goods_owner', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('channel', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hash_value', models.BooleanField(default=False)),
                ('txid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UpperToTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_to_task', to='payment.TaskItem')),
                ('upper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_to_task', to='payment.UpperPayment')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='LowerToTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_to_task', to='payment.LowerPayment')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_to_task', to='payment.TaskItem')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('serial_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(max_length=30)),
                ('seller', models.CharField(max_length=30)),
                ('buyer', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payment.InvoiceBatch')),
            ],
        ),
    ]
