# Generated by Django 2.2 on 2019-11-14 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191114_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowertoorder',
            name='lower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_to_order', to='payment.LowerPayment'),
        ),
        migrations.AlterField(
            model_name='lowertoorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_to_order', to='contract.OrderStart'),
        ),
    ]
