# Generated by Django 2.2 on 2019-11-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20191114_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='invoice_status',
            field=models.BooleanField(default=False),
        ),
    ]
