# Generated by Django 2.2 on 2019-11-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_taskitem_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='invoice_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskitem', to='payment.InvoiceBatch'),
        ),
    ]
