# Generated by Django 2.2.3 on 2019-09-20 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamename', models.CharField(max_length=20)),
                ('realname', models.CharField(max_length=20)),
                ('passwordword', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('telphone_num', models.CharField(max_length=20)),
                ('comment', models.TextField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ManyToManyField(related_name='user_settings', to='contract.Vendor')),
            ],
            options={
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
